version: "3.9"

services:
  postgres_db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: users_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  auth_service:
    build: .
    container_name: auth_service
    command: uvicorn main:app --host 0.0.0.0 --port 80
    environment:
      - DATABASE_URL=postgresql://myuser:mypassword@postgres_db:5432/users_db
    depends_on:
      - postgres_db
    ports:
      - "8000:80"

  test_runner:
    build: .
    container_name: test_runner
    command: pytest -v
    environment:
      - DATABASE_URL=postgresql://myuser:mypassword@postgres_db:5432/users_db
    depends_on:
      - postgres_db
      - auth_service

volumes:
  pgdata: